collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3960573
color:
  saturation: 0.7634408
  brandStrength: 1
  lightness: 0.5268817
  brandColors:
    - '#FFFFFF'
    - '#B6CBC4'
    - '#08090B'
    - '#7D7165'
    - '#673729'
  rhythmicContrast: 0.7437276
layout_spectrum: 1
name: Sparklers
